### ISSUE TITLE
Access forbidden issue.

### ISSUE THREAD

**Issue by akhilesh-k** [akhilesh-k/metaqp-test#15]
Some specific papers have access forbidden. Please look into it.

https://www.jyc.co.in/metaqp/Library/2015/2015%20July%20-%20Dec/Exam.%20T-%201,%20Sept.%202015/ECE/Theory%20and%20Application%20of%20Control%20System%20(10B11WEC515)%20T-%201%20September,%202015%20(Sem%205).pdf

**Comment by prashasy** [comment]
Let me check

**Comment by akhilesh-k** [comment]
Sure thing!

**Comment by prashasy** [comment]
<img width="935" alt="screen shot 2019-02-20 at 5 26 05 pm" src="https://user-images.githubusercontent.com/24864001/53090152-8d7f1c00-3534-11e9-8e2e-5c6918ecde9d.png">

It has the correct permissions granted. Any ideas why this might be still in-accessible?

**Comment by prashasy** [comment]
Other files with the same access permissions are opening fine

**Comment by akhilesh-k** [comment]
I guess, it's happening just for this file. Rest other files from 2015 are having no such issues.

**Comment by prashasy** [comment]
Since we have successfully migrated to AWS, I am closing this issue now.
