### ISSUE TITLE
Should we remove badges?

### ISSUE THREAD

**Issue by akhilesh-k** [akhilesh-k/metaqp-test#9]
Yesterday I and @prashasy were discussing about involving a greater community to the metaJUIT, where we felt the need to branding metaqp as something built by community for community. 

What do you feel @lavish-kumar ?

**Comment by prashasy** [comment]
I think metaJUIT being a community project, should be branded as a public open source project and individual developer names tend to make things look private. I believe removing developer names and projecting it as a community project would help us get a better reach and acceptance

**Comment by lavish-kumar** [comment]
okay, then we should remove them.

**Comment by akhilesh-k** [comment]
Done and closing.
